server:
  port: 9010

spring:
  datasource:
    master:
      name: master
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat,wall,log4j
      initialSize: 10
      maxActive: 50
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 120000
      minEvictableIdleTimeMillis: 300000
      minIdle: 10
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      type: com.alibaba.druid.pool.DruidDataSource
      useGlobalDataSourceStat: false
      validationQuery: SELECT 1 FROM DUAL
    slave:
      name: slave1
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat,wall,log4j
      initialSize: 10
      maxActive: 50
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 120000
      minEvictableIdleTimeMillis: 300000
      minIdle: 10
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      type: com.alibaba.druid.pool.DruidDataSource
      useGlobalDataSourceStat: false
      validationQuery: SELECT 1 FROM DUAL
  mybatis:
    typeAliasesPackage: com.opg.steam.simple.app01.common.dal.persistant
    mappingXml: classpath:mapper/*.xml
  pageHelper:
    dialect: mysql
    rowBoundsWithCount: true
    pageSizeZero: true
    reasonable: true
    supportMethodsArguments:
    offsetAsPageNum: true
    params: count=countSql
    returnPageInfo: check

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

test:
  properties:
    world: 999999999

druid:
  config:
    enabled: true
    urlMapping: /druid/*
    resetEnable: false
    allow:
    deny:
    loginUsername: baily
    loginPassword: 123456
    exclusions:  /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
    profileEnable: true
    urlPatterns: /*