server:
  tomcat:
    uri-encoding: UTF-8
  port: 9010

spring:
  application:
    name: wedding-invitation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

test:
  properties:
    world: 999999999

druid:
  config:
    enabled: true
    urlMapping: /druid/*
    resetEnable: false
    allow:
    deny:
    loginUsername: baily
    loginPassword: 123456
    exclusions:  /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
    profileEnable: true
    urlPatterns: /*